import React from "react";

export const HomePage = React.lazy(() => import('./HomePage/HomePage'))
export const OfertaEducativaPage = React.lazy(() => import('./OfertaEducativaPage/OfertaEducativaPage'))
export const CarrerasPage = React.lazy(() => import('./CarrerasPage/CarrerasPage'))
export const NotFoundPage = React.lazy(() => import("./NotFoundPage/NotFoundPage"))
export const LegislacionUniversitariaPage = React.lazy(() => import('./LegislacionUniversitaria/LegislacionUniversitariaPage'))
export const CertificacionesPage = React.lazy(() => import('./CertificacionesPage/CertificacionesPage'))
export const CuadriculaLogosPage = React.lazy(() => import('./CuadriculaLogosPage/CuadriculaLogosPage'))
export const EducacionContinuaPage = React.lazy(() => import('./EducacionContinuaPage/EducacionContinuaPage'))
export const SubsidiosPage = React.lazy(() => import('./SubsidiosPage/SubsidiosPage'))
export const DirectorioPage = React.lazy(() => import('./DirectorioPage/DirectorioPage'))
export const AcademiaMatematicasPage = React.lazy(() => import('./AcademiaMatematicasPage/AcademiaMatematicasPage'))
export const BolsaTrabajoPage = React.lazy(() => import('./BolsaTrabajoPage/BolsaTrabajoPage'))
export const EmprendedoresPage = React.lazy(() => import('./EmprendedoresPage/EmprendedoresPage'))
export const Art36Page = React.lazy(() => import('./Art36Page/Art36Page'))
export const TestPage = React.lazy(() => import("./TestPage/TestPage"))
export const IgualdadPage = React.lazy(() => import("./IgualdadPage/IgualdadPage"))
export const PlanAnualPage = React.lazy(() => import("./PlanAnualPage/PlanAnualPage"))
export const ContraloriaSocialPage = React.lazy(() => import("./ContraloriaSocial/ContraloriaSocialPage"))
export const Prodep2020Page = React.lazy(() => import("./ContraloriaSocial/Prodep2020"))
export const Prodep2023Page = React.lazy(() => import("./ContraloriaSocial/Prodep2023"))
export const Pfce2020Page = React.lazy(() => import("./ContraloriaSocial/Pfce2020Page"))